export const ADMIN_LIST_USERS_REQUEST = 'ADMIN_LIST_USERS_REQUEST'
export const ADMIN_LIST_USERS_SUCCESS = 'ADMIN_LIST_USERS_SUCCESS'
export const ADMIN_LIST_USERS_FAIL = 'ADMIN_LIST_USERS_FAIL'
export const ADMIN_LIST_USERS_RESET = 'ADMIN_LIST_USERS_RESET'

export const ADMIN_DELE_USER_REQUEST = 'ADMIN_DELE_USER_REQUEST'
export const ADMIN_DELE_USER_SUCCESS = 'ADMIN_DELE_USER_SUCCESS'
export const ADMIN_DELE_USER_FAIL = 'ADMIN_DELE_USER_FAIL'
export const ADMIN_DELE_USER_RESET = 'ADMIN_DELE_USER_RESET'

export const ADMIN_UPDATE_USER_REQUEST = 'ADMIN_UPDATE_USER_REQUEST'
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS'
export const ADMIN_UPDATE_USER_FAIL = 'ADMIN_UPDATE_USER_FAIL'
export const ADMIN_UPDATE_USER_RESET = 'ADMIN_UPDATE_USER_RESET'

export const ADMIN_DELE_PRODUCT_REQUEST = 'ADMIN_DELE_PRODUCT_REQUEST'
export const ADMIN_DELE_PRODUCT_SUCCESS = 'ADMIN_DELE_PRODUCT_SUCCESS'
export const ADMIN_DELE_PRODUCT_FAIL = 'ADMIN_DELE_PRODUCT_FAIL'

export const ADMIN_CRE_PRODUCT_REQUEST = 'ADMIN_CRE_PRODUCT_REQUEST'
export const ADMIN_CRE_PRODUCT_SUCCESS = 'ADMIN_CRE_PRODUCT_SUCCESS'
export const ADMIN_CRE_PRODUCT_FAIL = 'ADMIN_CRE_PRODUCT_FAIL'
export const ADMIN_CRE_PRODUCT_RESET = 'ADMIN_CRE_PRODUCT_RESET'

export const ADMIN_UP_PRODUCT_REQUEST = 'ADMIN_UP_PRODUCT_REQUEST'
export const ADMIN_UP_PRODUCT_SUCCESS = 'ADMIN_UP_PRODUCT_SUCCESS'
export const ADMIN_UP_PRODUCT_FAIL = 'ADMIN_UP_PRODUCT_FAIL'
export const ADMIN_UP_PRODUCT_RESET = 'ADMIN_UP_PRODUCT_RESET'

export const ADMIN_NEW_SIZE_REQUEST = 'ADMIN_NEW_SIZE_REQUEST'
export const ADMIN_NEW_SIZE_SUCCESS = 'ADMIN_NEW_SIZE_SUCCESS'
export const ADMIN_NEW_SIZE_FAIL = 'ADMIN_NEW_SIZE_FAIL'

export const ADMIN_LIST_ORDERS_REQUEST = 'ADMIN_LIST_ORDERS_REQUEST'
export const ADMIN_LIST_ORDERS_SUCCESS = 'ADMIN_LIST_ORDERS_SUCCESS'
export const ADMIN_LIST_ORDERS_FAIL = 'ADMIN_LIST_ORDERS_FAIL'
export const ADMIN_LIST_ORDERS_RESET = 'ADMIN_LIST_ORDERS_RESET'

export const ADMIN_DELIVERED_REQUEST = 'ADMIN_DELIVERED_REQUEST'
export const ADMIN_DELIVERED_SUCCESS = 'ADMIN_DELIVERED_SUCCESS'
export const ADMIN_DELIVERED_FAIL = 'ADMIN_DELIVERED_FAIL'
export const ADMIN_DELIVERED_RESET = 'ADMIN_DELIVERED_RESET'